name: "SGCC Electricity"
version: "v1.6.8-test2"
slug: "sgcc_electricity"
description: "获取国网电费数据的插件"
url: "https://github.com/ARC-MX/sgcc_electricity_new"
arch:
  - aarch64
  - amd64
host_network: true
startup: application
boot: auto
init: false
image: "registry.cn-hangzhou.aliyuncs.com/arcw/sgcc_electricity-{arch}"
map:
  # - addons:rw
  - config:rw
  # - media:rw
  # - share:rw
options:
  PHONE_NUMBER: ""
  PASSWORD: ""  
  IGNORE_USER_ID: "xxxx,xxxx"
  ENABLE_DATABASE_STORAGE: false
  DB_NAME: "homeassistant.db"
  HASS_URL: "http://homeassistant.local:8123/"
  HASS_TOKEN: ""
  JOB_START_TIME: "07:00"
  RETRY_WAIT_TIME_OFFSET_UNIT: 15
  DATA_RETENTION_DAYS: 7
  RECHARGE_NOTIFY: false
  BALANCE: 5.0
  PUSHPLUS_TOKEN: "xxxx,xxxx"
schema:
  PHONE_NUMBER: str
  PASSWORD: password
  IGNORE_USER_ID: str
  ENABLE_DATABASE_STORAGE: bool
  DB_NAME: str
  HASS_URL: url
  HASS_TOKEN: str
  JOB_START_TIME: str
  RETRY_WAIT_TIME_OFFSET_UNIT: int(2,30)
  DATA_RETENTION_DAYS: int
  RECHARGE_NOTIFY: bool 
  BALANCE: float 
  PUSHPLUS_TOKEN: str
