version: "3"

services:
  app:
    env_file:
      - .env
    image: registry.cn-hangzhou.aliyuncs.com/arcw/sgcc_electricity:latest # for use docker.io: arcw/sgcc_electricity:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: sgcc_electricity
    networks:
      sgcc_network:
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    restart: unless-stopped
    volumes:
      - ./scripts:/app
    command: python3 main.py 

networks:
  sgcc_network:
